name: Deploy to S3
on:
  push: 
    branches: 
      - hotfix
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: debug1
        run: |
          pwd
          ls -l
          env
      - name: Checkout
        uses: actions/checkout@v3
      - name: debug2
        run: |
          pwd
          ls -l
          env
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 cp --recursive public/ s3://${S3_BUCKET}
